Traceback (most recent call last):
  File "main.py", line 242, in <module>
    main(**vars(FLAGS))
  File "main.py", line 215, in main
    model.train_model(train_loader, valid_loader, kwargs["epochs"], kwargs["learning_rate"], kwargs["log"], kwargs["save"])
  File "/Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/Models/bp.py", line 63, in train_model
    y_pred = self(x)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/emmagraham/Documents/GitHub/propagation/CLtargetprop/Models/bp.py", line 52, in forward
    output = torch.matmul(input, self.weight.t())
  File "/Users/emmagraham/anaconda3/envs/target-prop/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'bp_net' object has no attribute 'weight'